# Generated by Django 4.2.2 on 2023-06-30 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
