# Generated by Django 4.2.2 on 2023-07-03 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='createusermodel',
            table='users',
        ),
    ]
